### ISSUE TITLE
Option X not valid for openevse Max Current

### ISSUE THREAD

**Issue by Aephir** [firstof9/openevse#1]
Hi,

Thanks again for this. So far, I've only used it for info, but today I wanted to change the max current (via the `select.openevse_max_current`), but I get an error:

```
Option X not valid for openevse Max Current
```
I've tried with 12 and 16, the values I usually switch between from the openevse web UI.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/select/__init__.py:53
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:42:04 (4 occurrences)
Last logged: 10:42:24

[140521658835680] Option 12 not valid for openevse Max Current
[140521658835680] Option 16 not valid for openevse Max Current
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 53, in async_select_option
    raise ValueError(f"Option {option} not valid for {entity.name}")
ValueError: Option 12 not valid for openevse Max Current
```

**Comment by firstof9** [comment]
I'll take a look at this, thanks.
