### ISSUE TITLE
Unexpected error fetching OpenEVSE (openevse) data: string indices must be integers

### ISSUE THREAD

**Issue by ruimarinho** [firstof9/openevse#116]
I was looking at logs today and noticed there was this error popping out a few times, but I can't exactly pinpoint to a particular action:

```
ERROR (MainThread) [custom_components.openevse] Unexpected error fetching OpenEVSE (openevse) data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openevse/__init__.py", line 266, in _async_update_data
    await self.update_sensors()
```

**Comment by firstof9** [comment]
What version of the integration?

**Comment by ruimarinho** [comment]
I’m running b14.

**Comment by firstof9** [comment]
Try reinstalling the integration, I am unable to reproduce this error.
