### ISSUE TITLE
Plugin not working with last Home Assistant 2022.12.8 Frontend 20221213.1 -

### ISSUE THREAD

**Issue by NoRiCKaB3** [firstof9/openevse#117]
I updated HA few days ago, and since then the OpenEvse plugin is not working anymore.

On the logs I can see:

ERROR (MainThread) [custom_components.openevse] Error fetching OpenEVSE (openevse) data: 'utf-8' codec can't decode byte 0xff in position 158: invalid start byte

Also:

Logger: custom_components.openevse
Source: custom_components/openevse/__init__.py:242
Integration: OpenEVSE

Unexpected error fetching OpenEVSE (openevse).firmware data: 'version'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openevse/__init__.py", line 242, in _async_update_data
    self._data = await self._manager.firmware_check()
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__main__.py", line 440, in firmware_check
    _LOGGER.debug("Detected firmware: %s", self._config["version"])
KeyError: 'version'

Failing with last 2.1.6 and 2.1.7b14

Regards.

**Comment by firstof9** [comment]
What version of HA?
What firmware of OpenEVSE?

**Comment by NoRiCKaB3** [comment]
Home Assistant 2022.12.8 Frontend 20221213.1

FIrmware of OpenEVSE 8.2.2 with wifi firmware 4.1.7

**Comment by firstof9** [comment]
Looks like they changed the API in 4.1.7, I'll get a fix going.
