### ISSUE TITLE
KeyError: 'msg'

### ISSUE THREAD

**Issue by Aephir** [firstof9/openevse#121]
I've noticed this error in the HA logs. I haven't noticed anything not working, but to be fair, there's road construction, and the car hasn't been able to get to the charger for a few days.

I'm on integration v2.1.6, HACS v1.30.0, HA core 2023.1.7, and haOS 9.4.

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/openevse/switch.py:98
Integration: OpenEVSE
First occurred: 14:47:50 (1 occurrences)
Last logged: 14:47:50

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 325, in post
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 124, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/openevse/switch.py", line 98, in async_turn_on
    await getattr(self._manager, self.toggle_command)()
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 486, in toggle_override
    response = await self.send_command(command)
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 260, in send_command
    value = await self.process_request(url=url, method="post", rapi=data)
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 238, in process_request
    _LOGGER.error("%s", message["msg"])
KeyError: 'msg'

```

**Comment by firstof9** [comment]
This would be an error from the library, not the integration. I'll move this issue over.
