### ISSUE TITLE
New Beta fails to start due to missing version in pypi

### ISSUE THREAD

**Issue by omriasta** [firstof9/openevse#19]
New pre-release relies on python-openevse-http v0.1.13 not yet available on pypi....

**Comment by firstof9** [comment]
Should be resolved now, you'll need to restart Home Assistant.

**Comment by omriasta** [comment]
just saw it pop up on pypi :) now getting:
```
Logger: homeassistant.setup
Source: custom_components/openevse/const.py:187
Integration: OpenEVSE
First occurred: 4:13:06 PM (1 occurrences)
Last logged: 4:13:06 PM

Setup failed for openevse: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/openevse/__init__.py", line 19, in <module>
    from .const import (
  File "/config/custom_components/openevse/const.py", line 187, in <module>
    device_class=DEVICE_CLASS_POWER,
NameError: name 'DEVICE_CLASS_POWER' is not defined
```

**Comment by firstof9** [comment]
I'll get it sorted shortly, thanks :+1:

**Comment by omriasta** [comment]
no prob! Let me know if you need me to test...heading out in a bit but should be home in a couple of hours...

**Comment by firstof9** [comment]
Fixed in latest beta. :beers:

**Comment by omriasta** [comment]
Looks good!
