### ISSUE TITLE
Error after upgrading to 2.1.18 "MissingSerial"

### ISSUE THREAD

**Issue by Aephir** [firstof9/openevse#197]
I've been using this great integration for more than a year, but after upgrading 2.1.18 (and persisting in 2.1.19) I've been getting this error, and the device is no longer available in HA:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/openevse/__init__.py:71
Integration: OpenEVSE (documentation, issues)
First occurred: March 25, 2023 at 13:16:56 (2 occurrences)
Last logged: March 25, 2023 at 20:44:58

Error setting up entry OpenEVSE for openevse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openevse/__init__.py", line 71, in async_setup_entry
    data = await manager.test_and_get()
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__main__.py", line 194, in test_and_get
    raise MissingSerial
openevsehttp.exceptions.MissingSerial
```

EDIT: Using the openevse web interface works fine.

**Comment by Aephir** [comment]
You're fast. Thanks a lot!
