### ISSUE TITLE
Restart EVSE from integration shows an error

### ISSUE THREAD

**Issue by dml33** [firstof9/openevse#315]
Hi.

OpenEVSE Firmware: v5.0.2
HA Integration 2.1.3.4

I noticed that the car was not starting to charge. Then, I noticed that OpenEVSE time and local_time were actually 2 days ago, so I wanted to restart it from the HA integration. I pressed "PRESS" in `Restart EVSE` and an error showed up at the bottom bar.

![image](https://github.com/firstof9/openevse/assets/25033130/5b8be4af-cf34-439f-8e4d-64595b141701)

I pressed it a couple of times, but only that error appeared. Then, a minute or two later I noticed that it had actually restarted and started working again.

This error was written in logs:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 00:17:39 (2 occurrences)
Last logged: 00:19:34

[140328406356032]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 139, in _async_press_action
    await self.async_press()
  File "/config/custom_components/openevse/button.py", line 64, in async_press
    await getattr(self.manager, self._key)()
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 487, in restart_evse
    response = await self.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 171, in send_command
    value = await self.process_request(url=url, method="post", rapi=data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 144, in process_request
    raise ParseJSONError
openevsehttp.exceptions.ParseJSONError
```

Maybe you should take a look at it.

Thanks!

**Comment by firstof9** [comment]
Would need the actual error from the `home-assistant.log` file not the UI log message.

**Comment by dml33** [comment]
Morning.

Here it is

![image](https://github.com/firstof9/openevse/assets/25033130/3ad189f0-7b74-40d8-ae03-4cb1ceefc65f)

![image](https://github.com/firstof9/openevse/assets/25033130/3b6782aa-d341-424d-883b-5143be40864e)

Best regards.

**Comment by firstof9** [comment]
That's hard to read, please don't post pictures of text, just copy/paste the text in the future please.

This is stating that your OpenEVSE is unreachable, this is an issue with your network not the integration.

**Comment by dml33** [comment]
Hi.

Sorry for the images but I couldn't copy&paste the text. I had to hurry for a trip and it was the only way I could manage at that time.

More details in the User Interface about the error would be nice for the user to retry the command or try something else.

Thanks.

**Comment by firstof9** [comment]
> Sorry for the images but I couldn't copy&paste the text. I had to hurry for a trip and it was the only way I could manage at that time.

No worries.

> More details in the User Interface about the error would be nice for the user to retry the command or try something else.

This is a weird failing on the Home Assistant end of things, I am not sure why they're _only_ putting the traceback in to the logger bit in the UI. This is why I usually end up asking for log entries, as they contain far more insight into the issue at hand.

**Comment by MilorES** [comment]
![imagen](https://github.com/firstof9/openevse/assets/7502697/03f1777f-b8fd-4be7-b8d2-619c6957c235)

Same problem here. Same problem here. I have a username and password. 

![imagen](https://github.com/firstof9/openevse/assets/7502697/a992d9f1-537a-4558-9cb2-6264cdf758b6)

The upper one does not work but the lower one that restarts the WIFI does so correctly.

`2024-03-26 18:52:50.340 ERROR (MainThread) [openevsehttp.__main__] Error 400: RAPI_RESPONSE_BLOCKED
2024-03-26 18:52:50.342 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546713387584] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 139, in _async_press_action
    await self.async_press()
  File "/config/custom_components/openevse/button.py", line 64, in async_press
    await getattr(self.manager, self._key)()
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 487, in restart_evse
    response = await self.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 171, in send_command
    value = await self.process_request(url=url, method="post", rapi=data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 144, in process_request
    raise ParseJSONError
openevsehttp.exceptions.ParseJSONError`

It will be because in V5 the RAPI writing commands are blocked. Those who have V4 should have no problems.
Should they be done in http API?

**Comment by firstof9** [comment]
> Should they be done in http API?

The calls are done via the HTTP API, what version of the integration are you using?

**Comment by firstof9** [comment]
Oh wait, I do see where I need to update the library. My mistake.

**Comment by firstof9** [comment]
This should be fixed in `2.1.35`.

**Comment by robotsflo** [comment]
Hello, i have the same problem when i try to chnage current value : 
OpenEVSE Firmware: v5.1.0
HA Integration 2.1.35

`Error 400: RAPI_RESPONSE_BLOCKED`

**Comment by robotsflo** [comment]
`2024-04-19 10:43:49.983 DEBUG (MainThread) [custom_components.openevse.select] Command: set_current Option: 15
2024-04-19 10:43:49.999 ERROR (MainThread) [openevsehttp.__main__] Error 400: RAPI_RESPONSE_BLOCKED
File "/config/custom_components/openevse/select.py", line 94, in async_select_option
File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 451, in set_current
File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 171, in send_command
File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 144, in process_request
openevsehttp.exceptions.ParseJSONError`

**Comment by firstof9** [comment]
This isn't the same issue, please open a new issue, also please provide a full debug log.
Once in debug logging mode, reload the integration.

Thanks.
