### ISSUE TITLE
[Bug]: Controling error with compiled firmware

### ISSUE THREAD

**Issue by robotsflo** [firstof9/openevse#343]
### The problem

Hello, 
I can't control anything with your integration, after reading the logs I see this (below) : 

I have a self compiled firmware that have not version label in webui 
![image](https://github.com/firstof9/openevse/assets/32175029/022e566c-4655-4023-af3a-9e44020aed20)

Your integration can do an exception with generic : "local___modified" version ? 

`
2024-05-23 23:24:23.440 DEBUG (MainThread) [custom_components.openevse.switch] switch [OpenEVSE: openevse-2564 Sleep Mode]: charging
2024-05-23 23:24:23.441 DEBUG (MainThread) [custom_components.openevse.switch] switch [OpenEVSE: openevse-2564 Sleep Mode (new)]: charging
2024-05-23 23:24:23.441 DEBUG (MainThread) [custom_components.openevse.switch] switch [OpenEVSE: openevse-2564 Manual Override]: True
2024-05-23 23:24:23.441 DEBUG (MainThread) [custom_components.openevse.switch] switch [OpenEVSE: openevse-2564 Solar PV Divert]: False
2024-05-23 23:24:24.405 DEBUG (MainThread) [custom_components.openevse.switch] switch [OpenEVSE: openevse-2564 Sleep Mode (new)]: charging
2024-05-23 23:24:24.405 DEBUG (MainThread) [openevsehttp.__main__] Detected firmware: local___modified
2024-05-23 23:24:24.405 DEBUG (MainThread) [openevsehttp.__main__] Filtered firmware: None
2024-05-23 23:24:24.405 DEBUG (MainThread) [openevsehttp.__main__] Non-semver firmware version detected.
2024-05-23 23:24:24.405 DEBUG (MainThread) [openevsehttp.__main__] Feature not supported for older firmware.
2024-05-23 23:24:24.405 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139895334908224] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/openevse/switch.py", line 97, in async_turn_on
    await self._manager.release_claim()
  File "/usr/local/lib/python3.12/site-packages/openevsehttp/__main__.py", line 809, in release_claim
    raise UnsupportedFeature
openevsehttp.exceptions.UnsupportedFeature
`

### What version of Home Assistant?

core-2024.5.4

### What version of OpenEVSE?

2.1.40

**Comment by firstof9** [comment]
Recompile your firmware with proper semantic versioning.
