### ISSUE TITLE
Unable to toggle "sleep mode" after upgrading to Hass 2022.4

### ISSUE THREAD

**Issue by Aephir** [firstof9/openevse#39]
Hi, as the title says, after I upgraded to Home Assistant v2022.4.x (tried a few different, I'm on 2022.4.5 now), I have not been able to call the "sleep mode" from Home Assistant.

It looks like it's getting updates from OpenEVSE (e.g. the "sensor.openevse_charging_current" sensor in Home Assistant changes when car is charging), but if I try to toggle the sleep mode, I get this notice:
<img width="918" alt="Screenshot 2022-04-16 at 11 13 00" src="https://user-images.githubusercontent.com/20152788/163669550-45035d0d-4cfd-42ba-8b4c-5ff8b6d65935.png">

I can see a few entries in the logs (OpenEVSE is conncted to, and reachable at http://10.0.20.27), this one seems to come every time I try to toggle sleep mode:

<details>

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/openevse/switch.py:98
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:15:27 (1 occurrences)
Last logged: 18:15:27

[140114950482000] 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/openevse/switch.py", line 98, in async_turn_on
    await getattr(self._manager, self.toggle_command)()
  File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 440, in toggle_override
    response = await self.send_command(command)
  File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 237, in send_command
    value = await self.process_request(url=url, method="post", data=data)
  File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 208, in process_request
    message = await resp.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
```

</details>

I've also seen these a few times (though though it might only have been while using integration v2.1.1, before upgrading to the beta):

<details>

```
Logger: openevsehttp
Source: /usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py:143
First occurred: April 15, 2022, 19:32:15 (4 occurrences)
Last logged: April 15, 2022, 19:34:16

Websocket connection failed, retrying in 15s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
Websocket connection failed, retrying in 30s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
Websocket connection failed, retrying in 60s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
Websocket connection failed, retrying in 120s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
```

</details>

as well as:

<details>

```
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor (documentation, issues)
First occurred: April 15, 2022, 12:09:06 (2 occurrences)
Last logged: April 15, 2022, 12:09:06

Error adding entities for domain sensor with platform openevse
Error while setting up openevse platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

</details>

and

<details>

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_registry.py:529
Integration: Binary sensor (documentation, issues)
First occurred: April 15, 2022, 12:09:06 (2 occurrences)
Last logged: April 15, 2022, 12:09:06

Error adding entities for domain binary_sensor with platform openevse
Error while setting up openevse platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

</details>

I am on v2.1.2-b1 of the integration (seen from the file downloaded with the `download diagnostics` option from the integration page, though I first saw these issues before upgrading to the beta, while on v2.1.1).

**Comment by firstof9** [comment]
What firmware of OpenEVSE?

**Comment by Aephir** [comment]
I guess it's the `5.0.1` you're interested in?

<img width="426" alt="Screenshot 2022-04-17 at 18 35 41" src="https://user-images.githubusercontent.com/20152788/163723839-b7221be4-0085-408a-8519-02a1da06ea07.png">

**Comment by firstof9** [comment]
Wifi firmware sorry, looks like you're on `3.3.1`.
That's weird because the entity categories should be correct. Can you check your `const.py` and post the binary_sensors part?

**Comment by Aephir** [comment]
Sure, line 255 - 284 of `const.py`:

```
# key: name
BINARY_SENSORS: Final[dict[str, BinarySensorEntityDescription]] = {
    "ota_update": BinarySensorEntityDescription(
        name="OTA Update",
        key="ota_update",
        device_class=BinarySensorDeviceClass.UPDATE,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    "vehicle": BinarySensorEntityDescription(
        name="Vehicle Connected",
        key="vehicle",
        device_class=BinarySensorDeviceClass.PLUG,
    ),
    "manual_override": BinarySensorEntityDescription(
        name="Manual Override",
        key="manual_override",
        device_class=BinarySensorDeviceClass.POWER,
    ),
    "divert_active": BinarySensorEntityDescription(
        name="Divert Active",
        key="divert_active",
        device_class=BinarySensorDeviceClass.POWER,
    ),
    "using_ethernet": BinarySensorEntityDescription(
        name="Ethernet Connected",
        key="using_ethernet",
        device_class=BinarySensorDeviceClass.CONNECTIVITY,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
}
```

**Comment by firstof9** [comment]
You shouldn't be getting any `entity_category` errors, you'd have only seen them in the previous version.
I'll take a look at the sleep mode, it looks like a bug in the library.

**Comment by Aephir** [comment]
OK, sorry about the confusion about `entity_category`. Let me know if there's anything you need, or anything I can do to help.
