### ISSUE TITLE
[Feature Request]: Add feature to turn off LCD

### ISSUE THREAD

**Issue by silviudc** [firstof9/openevse#401]
### The feature

Would it be possible to add a button that toggles the LCD on and off?
I remember being able it to do in the past with a RAPI command

**Comment by firstof9** [comment]
There's no API function to disable a LCD.

**Comment by silviudc** [comment]
> There's no API function to disable a LCD.

Not disable it, but turn off the backlight I meant.

**Comment by KipK** [comment]
backlight should turn off itself when idle. 

You should ask on openevse_esp32 git as feature request to expose backlights control over http api.
Nows RAPI access has been removed, there's probably few features to expose over api.

**Comment by silviudc** [comment]
> #404 may solve your request, I'm not sure.

I think it would if the brightness can be set to 0 and switches off the backlight?

**Comment by firstof9** [comment]
> I think it would if the brightness can be set to 0 and switches off the backlight?

I'm not sure, but I've made it a dim-able light in Home Assistant, the feature will be in the next beta to try out.

**Comment by firstof9** [comment]
@silviudc have you tried the latest beta?

**Comment by silviudc** [comment]
@firstof9 
I was actually just about to ask as I saw the "light" being added to one of the recent releases but I am not seeing anything like that  after updating in the list of sensors coming from the integration.
Does it depend on the FW version of the station? I am on v5.0.2 and I updated to 5.10 a while back but they did something silly like LAN was turned off in that and was just wifi so I had to revert to 5.0.2

**Comment by firstof9** [comment]
Version "4.1.0" or higher. Please check what version of the integration is installed. It's currently in the beta releases.

**Comment by silviudc** [comment]
> Version "4.1.0" or higher. Please check what version of the integration is installed. It's currently in the beta releases.

I have 2.1.47-b2 currently installed, I should see a button or what type of sensor for this?

**Comment by firstof9** [comment]
It's a light entity here's mine:
![image](https://github.com/user-attachments/assets/a6707631-8383-4c53-ac6c-abe198f4789b)

**Comment by silviudc** [comment]
Yes that one is missing for me 
![image](https://github.com/user-attachments/assets/51da932d-6e57-4a6e-9c39-6b0e3c39c59c)
Restarted HA, EVSE, reloaded integration but it won't show up

**Comment by firstof9** [comment]
> Restarted HA, EVSE, reloaded integration but it won't show up

Check in `/config/custom_components/openevese/` and see if `light.py` exists.
If it doesn't, HACS has gone wonky, and you can manually drop the files from the ZIP into that path and restart HA.

**Comment by silviudc** [comment]
Yes it is there it seems

**Comment by firstof9** [comment]
> Yes it is there it seems

Seems your OpenEVSE isn't sending out led status messages then.
Which one do you have?

**Comment by silviudc** [comment]
This one https://shop.openenergymonitor.com/emonevse-wifi-connected-ev-charging-station-type-2/
It should work as I was able to turn off the backlight using RAPI in the past.
I'll try updating it to 5.1.2 tomorrow, seems like they fixed the LAN issue, see if that makes it show up

**Comment by firstof9** [comment]
If you do the debug logging and try adjusting the LED brightness from the OpenEVSE webui it should capture anything that comes over the websocket, or you can do the debugging from the openevse webui too.

**Comment by silviudc** [comment]
> If you do the debug logging and try adjusting the LED brightness from the OpenEVSE webui it should capture anything that comes over the websocket, or you can do the debugging from the openevse webui too.

Where is that option, for the brightness, don't remember seeing it anywhere?
![image](https://github.com/user-attachments/assets/9be0807f-8d23-4fb8-a6e5-236ebd18b80f)

**Comment by firstof9** [comment]
> Where is that option, for the brightness, don't remember seeing it anywhere?

Under `EVSE`, and `LED brightness` would be the very bottom.

![image](https://github.com/user-attachments/assets/756fa9f9-8534-48ea-b921-816e1067b6d8)


Debugging you can watch via `Developer` there and the button would be called just `Debug` that's the websocket that's being monitored.

**Comment by silviudc** [comment]
Looks like I don't have it which would explain why the integration doesn't expose it.
I'll try to update the FW now, see if it shows up

![image](https://github.com/user-attachments/assets/fb06440b-85ec-4508-94bd-b1a30264a1c0)

**Comment by firstof9** [comment]
Seems the blacklight isn't exposed. You may want to do like KipK stated here: https://github.com/firstof9/openevse/issues/401#issuecomment-2480154336

**Comment by silviudc** [comment]
I am seeing this error in the logs and I assume it's related to the feature but my station does not have it exposed?:
```
2025-03-20 16:36:05.969 ERROR (MainThread) [homeassistant.components.light] Error while setting up openevse platform for light: 'led_brightness'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/openevse/light.py", line 44, in async_setup_entry
    OpenEVSELight(config_entry, coordinator, LIGHT_TYPES[light], manager)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openevse/light.py", line 76, in __init__
    self._attr_brightness = coordinator.data[self._type]
                            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'led_brightness'
```
Anything to be done to ignore it (if it cannot set it up) in one of the future updates?

**Comment by firstof9** [comment]
Is this in the latest beta?

**Comment by firstof9** [comment]
Please see if `2.1.47-b9` resolves this for you.
