### ISSUE TITLE
[Bug]: Error fetching OpenEVSE Data with 2.1.47-b2 - UnsupportedFeature

### ISSUE THREAD

**Issue by Cadair** [firstof9/openevse#412]
### The problem

```
This error originated from a custom integration.

Logger: custom_components.openevse
Source: helpers/update_coordinator.py:379
integration: OpenEVSE (documentation, issues)
First occurred: 18 December 2024 at 13:57:00 (1017 occurrences)
Last logged: 12:32:57

Unexpected error fetching OpenEVSE (openevse) data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openevse/__init__.py", line 310, in _async_update_data
    await self.update_sensors()
  File "/config/custom_components/openevse/__init__.py", line 325, in update_sensors
    self.parse_sensors()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/openevse/__init__.py", line 397, in parse_sensors
    _sensor[light] = getattr(self._manager, sensor_property)
                     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openevsehttp/__main__.py", line 848, in led_brightness
    raise UnsupportedFeature
openevsehttp.exceptions.UnsupportedFeature
```

Looks like my firmware maybe doesn't support the light or something?

### What version of Home Assistant?

core-2024.12.4

### What version of OpenEVSE?

2.1.47-b2

**Comment by firstof9** [comment]
> ### What version of OpenEVSE?
> 2.1.47-b2

What version of OpenEVSE? (not the integration)

**Comment by Cadair** [comment]
> WiFi Firmware Version: 3.3.1

**Comment by firstof9** [comment]
Yup it's only supported in `4.1.0` or higher. It shouldn't block the integration tho. I'll get that fixed for ya.

**Comment by Cadair** [comment]
Thanks! I really should figure out how to update the firmware sometime.
