### ISSUE TITLE
Error adding integration

### ISSUE THREAD

**Issue by soloam** [firstof9/openevse#78]
I installed the latest version from this integration 2.1.6 (From HACS) on Home Assistant 2022.10.2 and when I go to integration and add it I get the message:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

What can it be?

Tks

**Comment by soloam** [comment]
I have this information when clicking on the integration:

````
2022-10-10 17:23:48.433 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.openevse.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/openevse/config_flow.py", line 21, in <module>
    class OpenEVSEFlowHandler(config_entries.ConfigFlow, domain=DOMAIN):
  File "/home/homeassistant/.homeassistant/custom_components/openevse/config_flow.py", line 33, in OpenEVSEFlowHandler
    self, user_input: dict[str, Any] | None = None
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2022-10-10 17:23:48.435 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration openevse: Exception importing custom_components.openevse.config_flow

````

**Comment by firstof9** [comment]
See if `2.1.7-b2` resolve the issue for you please.

**Comment by firstof9** [comment]
Thanks for confirming.
