### ISSUE TITLE
Unable to toggle override on 4.1.5.dev

### ISSUE THREAD

**Issue by ruimarinho** [firstof9/openevse#81]
I usually run dev builds on my OpenEVSE but it seems like the semver module doesn't like the `.dev` that is part of these builds. Maybe stripping `.dev` makes sense for this purpose?

```
home-assistant      | 2022-11-01 00:51:22.734 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140493510078048] Can't compare <unknown 4.1.5.dev> and <SemVer 4.0.0>
home-assistant      | Traceback (most recent call last):
home-assistant      |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
home-assistant      |     await hass.services.async_call(
home-assistant      |   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
home-assistant      |     future.result()  # pop exception if have
home-assistant      |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
home-assistant      |     await getattr(self._manager, self.toggle_command)()
home-assistant      |   File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 476, in toggle_override
```

**Comment by firstof9** [comment]
I'll need to strip it from inside the library.
