### ISSUE TITLE
Exposing missing RAPI `$FR` command

### ISSUE THREAD

**Issue by ruimarinho** [firstof9/openevse#91]
Hi @firstof9,

There are a number of RAPI commands that are not yet supported by the new [HTTP API](https://openevse.stoplight.io/docs/openevse-wifi-v4). 

While the documentation mentions RAPI commands should be sent preferably over MQTT, the reality is that OpenEVSE's MQTT client implementation has several reconnect bugs and often drops the connection to an MQTT server without ever recovering until a WiFi module restart is performed.

I believe `$FS` and `$FE` have been replaced by the `Manual Override` [endpoint to some extent](https://github.com/firstof9/python-openevse-http/blob/968cf7fd81a2461f8ab13b5eaf6da55f73086175/openevsehttp/__init__.py#L492-L496), but one particular RAPI command that is still very useful is `$FR`, allowing the _reset_ (restart) of the OpenEVSE controller. This is sometimes required when cars plugged into the charger go into a deep sleep mode and charging is not activated by simply enabling it (either via `$FE` or by setting manual override to `active`). There has been a previous attempt of fixing this by marking `sleep` as `disabled` in the WiFI UI configuration, but some cars still remain unresponsive.

[$FR](https://github.com/OpenEVSE/open_evse/blob/stable/firmware/open_evse/rapi_proc.h#L125) (and the buggy HTTP set divert mode) are two of the few commands that I still need to execute outside this custom component.

**Comment by firstof9** [comment]
I can make that into a `button` to call the `$FR`.

**Comment by firstof9** [comment]
Implemented in `2.1.7-b9`

**Comment by ruimarinho** [comment]
I'm getting this when I press Restart EVSE:

```
2022-11-05 22:37:21.956 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140651754166480] 'msg'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 116, in _async_press_action
    await self.async_press()
  File "/config/custom_components/openevse/button.py", line 69, in async_press
    await getattr(self.manager, self._key)()
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 563, in restart_evse
    response = await self.send_command(command)
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 260, in send_command
    value = await self.process_request(url=url, method="post", rapi=data)
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 238, in process_request
    _LOGGER.error("%s", message["msg"])
KeyError: 'msg'
```

**Comment by firstof9** [comment]
Ok that error is sorted in b10, you will still see an error from the library for now because it looks like the RAPI command times out due to the EVSE restart. I'll filter that out at in an update.

**Comment by firstof9** [comment]
Please see if this is still occurring in the latest release.
