### ISSUE TITLE
Error on integration setup with 2.1.7-b10

### ISSUE THREAD

**Issue by Cadair** [firstof9/openevse#97]
I just installed b10 (I jumped from 4 or 5 I think) and I hit the following error:

```


Logger: homeassistant.config_entries
Source: custom_components/openevse/__init__.py:103
Integration: OpenEVSE
First occurred: 15:00:12 (1 occurrences)
Last logged: 15:00:12
Error setting up entry OpenEVSE for openevse

Traceback (most recent call last):
  File "/config/custom_components/openevse/__init__.py", line 102, in get_firmware
    data = await manager.test_and_get()
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__init__.py", line 305, in test_and_get
    raise MissingSerial
openevsehttp.exceptions.MissingSerial

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openevse/__init__.py", line 66, in async_setup_entry
    model_info, sw_version = await get_firmware(manager)
  File "/config/custom_components/openevse/__init__.py", line 103, in get_firmware
    except OpenEVSE.MissingSerial as error:
AttributeError: type object 'OpenEVSE' has no attribute 'MissingSerial'

```

**Comment by firstof9** [comment]
Should be fixed in b11

**Comment by Cadair** [comment]
This error is fixed, I now get this with b11:

```


Logger: homeassistant.config_entries
Source: custom_components/openevse/__init__.py:108
Integration: OpenEVSE
First occurred: 15:23:21 (1 occurrences)
Last logged: 15:23:21
Error setting up entry OpenEVSE for openevse

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openevse/__init__.py", line 67, in async_setup_entry
    model_info, sw_version = await get_firmware(manager)
  File "/config/custom_components/openevse/__init__.py", line 108, in get_firmware
    if data["model"] != "unknown":
KeyError: 'model'

```

**Comment by firstof9** [comment]
Ouch, ok give me a few.
